spring:
  application:
    name: NonaCozi

  # Banco de dados
  datasource:
    driver-class-name: ${DATABASE_DRIVER} # Driver
    url: ${DATABASE_URL} # URL de conexão
    username: ${DATABASE_USERNAME} # Usuário
    password: ${DATABASE_PASSWORD} # Senha

  # Console do H2 (apenas para DEV)
  h2:
    console:
      enabled: true # Ativar console web H2
      path: /h2-console # Caminho console H2

  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update # Estratégia DDL (update ou create-drop APENAS para DEV)
    show-sql: false # Exibir queries SQL
    properties:
      hibernate.dialect: ${HIBERNATE_DIALECT} # Dialeto Hibernate

  # Configuração das mensagens em '.properties'
  messages:
    encoding: UTF-8 # Codificação das mensagens
    basename: messages # Nome base dos arquivos .properties

  # Configurações Springdoc (OpenAPI/Swagger UI)
  springdoc:
    api-docs:
      path: /v3/api-docs # Caminho especificação OpenAPI JSON/YAML
      enable: ${API_DOC_ENABLED} # Ativar geração OpenAPI

    swagger-ui:
      path: /swagger-ui.html # Caminho Swagger UI
      enabled: ${API_UI_ENABLED} # Ativar Swagger UI
      docExpansion: none # Expansão padrão UI
      filter: true # Habilitar filtro UI
      operationsSorter: method # Ordenar operações UI
      tagsSorter: alpha # Ordenar tags UI